general:
  project_name: atma2023
  input_path: ../data/input
  output_path: ../data/output
  save_name: exp4_early_up2
  seed: &seed 42
  cv: true
  wandb_desabled: false
  fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 5

#model: catboost
#xgb_params:
#  iterations: 100
#  loss_function: MultiRMSE
#  task_type: CPU

model_save: true