general:
  project_name: atma2023
  input_path: ../data/input
  output_path: ../data/output
  save_name: exp70_animenames
  seed: &seed 42
  cv: true
  wandb_desabled: false
  fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 5

train_noid: false

model:
  name: lightgbm
  params:
    objective: regression
    metric: rmse
    learning_rate": 0.1
    feature_fraction": 0.5
    bagging_freq": 0
    bagging_fraction": 1
    seed: *seed
model_noid:
  name: lightgbm
  params:
    objective: regression
    metric: rmse
    learning_rate": 0.1
    feature_fraction": 0.5
    bagging_freq": 0
    bagging_fraction": 1
    seed: *seed

model_save: false